Solution
mate-academy/js_numberdrome pull request #10
Opened 2019-06-02 23:38 UTC by Batsenko

2019-06-04 12:19 UTC, ost-ptk requested changes

2019-06-04 12:19 UTC, gestap commented on index.html
> +</html>
the document must end with one empty line

2019-06-04 12:19 UTC, gestap commented on main.js
> +}
the document must end with one empty line

2019-06-04 12:19 UTC, gestap commented on main.js
> +    constructor() {
use 2 whitespaces instead of 4

2019-06-04 12:19 UTC, gestap commented on main.js
> +class Numberdrome {
use strict mode

2019-06-07 13:50 UTC, ost-ptk approved these changes

2020-06-09 10:56 UTC, closed without merging