sol andrii
mate-academy/js_numberdrome pull request #17
Opened 2019-06-03 15:32 UTC by Laliquenoare

2019-06-04 11:54 UTC, ost-ptk requested changes

2019-06-04 11:54 UTC, gestap commented on main.js
> +      return this.num.reduce(((a, b) => a + b),0);
```suggestion
      return this.num.reduce(((a, b) => a + b), 0);
```

2019-06-04 11:54 UTC, gestap commented on main.js
> +    return this.num.reduce(((a, b) => a * b),1);
```suggestion
    return this.num.reduce(((a, b) => a * b), 1);
```

2019-06-04 11:54 UTC, gestap commented on main.js
> +}
the document must end with one empty line

2019-06-04 11:54 UTC, gestap commented on main.js
> +    if(this.num.length !== 0) {
no need for this checking

2019-06-05 07:36 UTC, ost-ptk requested changes

2019-06-05 07:36 UTC, gestap commented on main.js
> +    return Math.min(...this.num);
`...or throws an error if there are no numbers.`

2019-06-05 07:36 UTC, gestap commented on main.js
> +    return Math.max(...this.num);
`...or throws an error if there are no numbers.`

2019-06-10 07:53 UTC, ost-ptk approved these changes

2020-06-09 10:56 UTC, closed without merging