Anna Kondratiuk
mate-academy/js_numberdrome pull request #2
Opened 2019-06-01 08:30 UTC by annakondr

2019-06-04 12:03 UTC, ost-ptk requested changes

2019-06-04 12:03 UTC, gestap commented on src/main.js
> +            return this.numbers.reduce((a, b) => {return a + b})
no need for curly braces
https://github.com/mate-academy/style-guides/blob/master/javascript.md#arrows--implicit-return

2019-06-04 12:03 UTC, gestap commented on src/main.js
> +            return this.numbers.reduce((a, b) => {return a * b})
here too

2019-06-04 12:03 UTC, gestap commented on src/main.js
> +        return ('Error: The Numberdrome is empty')
you need to use `throw`
`... or throws an error ...`

2019-06-04 12:03 UTC, gestap commented on src/main.js
> +        return ('Error: The Numberdrome is empty')
here too

2019-06-04 12:03 UTC, gestap commented on src/main.js
> +            return Math.max.apply(null, this.numbers)
suggestion: you can use spread operator

2019-06-04 12:03 UTC, gestap commented on src/main.js
> +            return Math.min.apply(null, this.numbers)
suggestion: you can use spread operator

2019-06-05 18:50 UTC, ost-ptk approved these changes

2020-06-09 10:56 UTC, closed without merging