Solution
mate-academy/js_numberdrome pull request #20
Opened 2019-06-03 19:54 UTC by AlexHladun

2019-06-05 12:37 UTC, NclsVI requested changes

2019-06-05 12:37 UTC, nicholas38466 commented on script.js
> +    })
використай initialValue в reduce

2019-06-05 12:37 UTC, nicholas38466 commented on script.js
> +    })
використай initialValue в reduce

2019-06-05 12:37 UTC, nicholas38466 commented on script.js
> +    return Math.min.apply(null, this.listOfNumbers);
Spread syntax краще підійде
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Spread_syntax

2019-06-05 12:37 UTC, nicholas38466 commented on script.js
> +    })
https://developer.mozilla.org/uk/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

2019-06-07 05:48 UTC, NclsVI approved these changes

2020-06-09 10:56 UTC, closed without merging