solution
mate-academy/js_numberdrome pull request #21
Opened 2019-06-03 20:26 UTC by RMasnyuk

2019-06-04 15:34 UTC, ost-ptk requested changes

2019-06-04 15:34 UTC, gestap commented on .gitignore
> +.idea
the document must end with one empty line

2019-06-04 15:34 UTC, gestap commented on Numberdrome.js
> +    constructor() {
use 2 whitespaces instead of 4

2019-06-04 15:34 UTC, gestap commented on Numberdrome.js
> +    constructor() {
https://github.com/mate-academy/style-guides/blob/master/javascript.md#whitespace--spaces

2019-06-04 15:34 UTC, gestap commented on Numberdrome.js
> +        return this.numbers.length === 0 ? 0 : this.numbers.reduce((sum, current) => {
no need for a ternary operator, you have initialValue in `reduce`

2019-06-04 15:34 UTC, gestap commented on Numberdrome.js
> +        return this.numbers.length === 0 ? 1 : this.numbers.reduce((prod, current) => {
no need for a ternary operator, you have initialValue in `reduce`

2019-06-04 15:34 UTC, gestap commented on Numberdrome.js
> +            console.log(e);
you need to `throw an error` instead return undefined

2019-06-04 15:34 UTC, gestap commented on Numberdrome.js
> +            console.log(e);
you need to `throw an error` instead return undefined

2019-06-05 12:39 UTC, NclsVI approved these changes

2020-06-09 10:56 UTC, closed without merging