sol
mate-academy/js_numberdrome pull request #31
Opened 2019-10-09 17:56 UTC by dsrtF0x-git

2019-10-13 15:46 UTC, gestap commented on numberdrome.js
> +    this.list.splice(this.list.indexOf(n), 1);
зроби перевірку на неіснуючі цифри

2019-10-13 15:46 UTC, gestap commented on numberdrome.js
> +    return this.list.length === 0 ? `Your list is empty` : Math.min(...this.list);
```suggestion
    return this.list.length ? Math.min(...this.list) : `Your list is empty`;
```

2019-10-15 09:07 UTC, 8hokage requested changes

2019-10-15 09:07 UTC, earthhuman41 commented on numberdrome.js
> +    if (this.list.includes(n)) {
Зачем делать дополнительно includes если ты можешь просто значение indexOf вынести в переменную и подставлять куда надо

2019-10-16 08:17 UTC, earthhuman41 commented on numberdrome.js
> +    this.list.push(n);
Здесь лучше делать проверку является n числом

2019-10-16 08:17 UTC, 8hokage approved these changes

2019-10-16 08:18 UTC, 8hokage approved these changes

2020-06-09 10:56 UTC, closed without merging