Solution
mate-academy/js_numberdrome pull request #32
Opened 2019-10-09 20:31 UTC by nikakarelets

2019-10-11 12:32 UTC, 8hokage requested changes

2019-10-11 12:32 UTC, earthhuman41 commented on numberdrome.js
> +        return  Math.min.apply(null, this.numbers)
Зачем вызывать через apply если можно просто Math.min(this.numbers)

2019-10-11 12:32 UTC, earthhuman41 commented on numberdrome.js
> +        return Math.max.apply(null, this.numbers)
Тоже самое, просто Math.max(this.numbers)

2019-10-11 12:32 UTC, earthhuman41 commented on numberdrome.js
> +        try {
Не пойму логику этого обработчика зачем тебе делать try если внутри ты все равно при условии выкинешь ошибку? И больше ничего. Убери try catch и оставь просто if

2019-10-11 12:32 UTC, earthhuman41 commented on numberdrome.js
> +        if (!isNaN(n)) {
Еще наверное стоит делать проверку число ли это,  ведь прийти может и строка или объект

2019-10-11 12:32 UTC, earthhuman41 commented on numberdrome.js
> +        let index = this.numbers.indexOf(n);
А что если n будет не найден? У тебя тогда в индекс запишется в  index -1 и далее удалится последний элемент т.к если в splice написать отрицательный индекс, то он будет считать с конца

2019-10-15 08:55 UTC, 8hokage approved these changes

2020-06-09 10:56 UTC, closed without merging