Kisilov
mate-academy/js_numberdrome pull request #37
Opened 2019-10-10 12:19 UTC by Kisilov-Vadim

2019-10-13 15:48 UTC, gestap commented on src/numberDrome.js
> +    console.log(this.numbersArr.reduce((sum, current) => sum + current));
методи мають повертати занчення, а не консолити

2019-10-15 09:02 UTC, 8hokage requested changes

2019-10-15 09:02 UTC, earthhuman41 commented on src/numberDrome.js
> +    return Math.min.apply(null, this.numbersArr);
Зачем вызывать через apply? Можно ведь просто min() max()

2019-10-16 10:21 UTC, 8hokage approved these changes

2020-06-09 10:56 UTC, closed without merging