Solution
mate-academy/js_numberdrome pull request #38
Opened 2019-10-10 13:06 UTC by chepa17

2019-10-11 11:52 UTC, 8hokage requested changes

2019-10-11 11:52 UTC, earthhuman41 commented on js_numbersdrome.js
> +    for (let num of this.list) {
А теперь попробуй реализовать методы min() max() через Math.max() и Max.min()

2019-10-11 11:52 UTC, earthhuman41 commented on js_numbersdrome.js
> +    for (let num of this.list) {
Попробуй здесь использовать reduce

2019-10-11 11:52 UTC, earthhuman41 commented on js_numbersdrome.js
> +      res += num;
Попробуй здесь использовать reduce

2019-10-11 11:54 UTC, 8hokage requested changes

2019-10-11 11:54 UTC, earthhuman41 commented on js_numbersdrome.js
> +    this.list = new Set();
В задании не говорилось, что все числа должны быть уникальными,  Set сделает их такими

2019-10-13 10:02 UTC, 8hokage approved these changes

2020-06-09 10:56 UTC, closed without merging