solution
mate-academy/js_numberdrome pull request #44
Opened 2019-10-11 11:37 UTC by kostya-flern

2019-10-13 15:41 UTC, gestap commented on main.js
> +    } else {
else зайвий

2019-10-13 15:41 UTC, gestap commented on main.js
> +    } else {
```suggestion
    }
```

2019-10-13 15:41 UTC, gestap commented on main.js
> +    } else {
тут теж

2019-10-13 15:41 UTC, gestap commented on main.js
> +    } else {
тут теж

2019-10-13 15:41 UTC, gestap commented on main.js
> +    } else {
тут теж

2019-10-13 15:41 UTC, gestap commented on main.js
> +    this.numberdrome = new Set();
в умові не сказано що номери мають бути унікальними

2019-10-13 15:41 UTC, gestap commented on main.js
> +    if (this.setlLength) {
думаю такий запис може призвести до неявних помилок

2019-10-13 15:41 UTC, gestap commented on main.js
> +    if (this.setlLength) {
краще писати 
```suggestion
    if (!this.numberdrome.length) {
```

2019-10-15 09:29 UTC, 8hokage requested changes

2019-10-15 09:29 UTC, earthhuman41 commented on main.js
> +    this.numberdrome.splice(this.numberdrome.indexOf(n), 1);
Тебе нужно делать проверку существует ли элемент в массиве иначе indexOf вернет -1 и splice удалит с конца

2019-10-15 09:29 UTC, earthhuman41 commented on main.js
> +    let myArr = Array.from(this.numberdrome);
Тебе не нужно делать копию reduce не мутирует массив а возвращает просто конечное значение вычислений

2019-10-16 14:56 UTC, 8hokage approved these changes

2020-06-09 10:56 UTC, closed without merging