Solution
mate-academy/js_numberdrome pull request #46
Opened 2019-10-11 14:26 UTC by ITStan

2019-10-13 10:31 UTC, 8hokage requested changes

2019-10-13 10:31 UTC, earthhuman41 commented on src/numberdrome.js
> +    this.list.splice(this.list.indexOf(n), 1);
Лучше сделай проверку есть ли такое число в списке иначе indexOf вернет -1  и splice будет удалять с конца

2019-10-15 09:04 UTC, 8hokage requested changes

2019-10-15 09:04 UTC, earthhuman41 commented on src/numberdrome.js
> +    this.list.push(n);
Добавь проверку является ли n числом

2019-10-16 08:25 UTC, 8hokage requested changes

2019-10-16 08:25 UTC, earthhuman41 commented on src/numberdrome.js
> +    if(!isNaN(n)){   // проверка, является ли n числом
Это не проверка на число, если я передам строку она все равно запушится делай проверку так `typeof n === 'number'`

2019-10-16 08:29 UTC, 8hokage approved these changes

2020-06-09 10:56 UTC, closed without merging