solution
mate-academy/js_numberdrome pull request #49
Opened 2019-10-14 21:35 UTC by lubremets

2019-10-15 09:24 UTC, 8hokage requested changes

2019-10-15 09:24 UTC, earthhuman41 commented on src/style.js
> +      this.arr.splice(indexOf(n), 1);
Зачем ты два раза делаешь indexOf? Лучше вынеси в переменную

2019-10-15 09:24 UTC, earthhuman41 commented on src/style.js
> +    this.arr.forEach(item => product *= item);
Здесь больше подойдет reduce

2019-10-15 09:24 UTC, earthhuman41 commented on src/style.js
> +    this.arr.forEach(item =>  result += item);
Здесь больше подойдет reduce

2019-10-16 15:00 UTC, 8hokage approved these changes

2019-10-16 15:00 UTC, earthhuman41 commented on src/style.js
> +    return this.arr.reduce((accumulator, currentValue) => (accumulator *= currentValue), 1);
Здесь можно просто accumulator * без =

2020-06-09 10:56 UTC, closed without merging