solution
mate-academy/js_numberdrome pull request #51
Opened 2019-10-16 11:28 UTC by ZelenskiyS

2019-10-16 15:11 UTC, 8hokage requested changes

2019-10-16 15:11 UTC, earthhuman41 commented on main.js
> +        this.list.forEach(value => result += value);
Тут лучше подойдет reduce

2019-10-16 15:11 UTC, earthhuman41 commented on main.js
> +        this.list.forEach(value => result *= value);
Тут лучше подойдет reduce

2019-10-16 15:11 UTC, earthhuman41 commented on main.js
> +        this.list.push(+num);
Добавь тут проверку является ли num числом или строкой иначе будет ошибке

2019-10-22 14:31 UTC, 8hokage requested changes

2019-10-22 14:31 UTC, earthhuman41 commented on main.js
> +        this.list.splice(this.list.indexOf(num), 1);
Здесь делай проверку на наличие num в массиве иначе индексоф вернет -1 и splice удалит с конца

2020-06-09 10:56 UTC, closed without merging